# Generated by Django 4.0.4 on 2022-04-30 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_rename_details_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='fashion',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
