# Generated by Django 4.0.4 on 2022-05-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_category_fashion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='fashion',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fashion',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
